FROM haproxy:1.8

RUN apt-get update \
	&& apt-get install -y --no-install-recommends \
		openssl \
	&& rm -rf /var/lib/apt/lists/*

COPY docker-entrypoint-custom.sh /
COPY haproxy.cfg /usr/local/etc/haproxy/

ENTRYPOINT ["/docker-entrypoint-custom.sh"]
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]