version: "2"

services:
  wordpress:
    image: wordpress:latest
    environment: 
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    restart: always
    volumes:
      - www-volume:/var/www/html

  haproxy:
    image: stiller/haproxy:selfsigned
    ports: 
      - 80:80
      - 443:443
    restart: always

volumes: 
  www-volume:
    driver: azurefile
    driver_opts:
      share: wordpress