version: "2"

services:
  wordpress:
    image: wordpress:latest
    ports:
      - 80:80
    environment: 
      - WORDPRESS_DB_HOST
      - WORDPRESS_DB_USER
      - WORDPRESS_DB_PASSWORD
    restart: always
    volumes:
      - www-volume:/var/www/html

volumes: 
  www-volume:
    driver: azurefile
    driver_opts:
      share: wordpress